---
- name: Ansible's Enviroment
  hosts: localhost
  become: yes
  gather_facts: no

  tasks:
    - name: Add "/etc/hosts"
      blockinfile:
        dest: /etc/hosts
        block: |
          192.168.1.10 server
          192.168.1.11 node01
          192.168.1.12 node02
          192.168.1.13 node03
          192.168.1.14 node04
          192.168.1.15 node05

    - name: Add "/etc/ansible/hosts"
      blockinfile:
        dest: /etc/ansible/hosts
        block: |
          [CentOS]
          node01
          node02
          
          [Ubuntu]
          node03
          node04
          
          [Windows]
          node05 ansible_connection=winrm ansible_ssh_user=vagrant ansible_ssh_port=5985
          
     # pip version error ??
     # python version 2.7 => 3 upgrade 
     # 0. mv /usr/bin/python /usr/bin/python_bak
     # 0-1. ln -s /usr/bin/python3 /usr/bin/python
     # 1. vi /usr/bin/yum 
     # 2. #!/usr/bin/python => /usr/bin/python2
     # 3. vi /usr/libexec/urlgrabber-ext-down
     # 4. #!/usr/bin/python => /usr/bin/python2.7
     # ????????????????????????????????????
     # https://www.jacobbaek.com/1358
     
    - name : Install pip
      yum:
        name: python-pip
        state: present
      
    - name : Install pywinrm
      pip:
        name: pywinrm
        state: present
        
    - name : Install sshpass
      yum:
        name: sshpass
        state: present
