---
- name: Remove nginx
  hosts: CentOS
  gather_facts: no
  become: yes

  tasks:
    - name: remove epel-release
      yum:
        name: epel-release 
        state=absent
    - name: remove nginx
      yum:
        name: nginx 
        state=absent 
