---
- name: Ansible's Enviroment
  hosts: localhost
  become: yes
  gather_facts: no

  tasks:
    - name: Add "/etc/hosts"
      blockinfile:
        dest: /etc/hosts
        block: |
          192.168.1.10 server
          192.168.1.11 node01
          192.168.1.12 node02

    - name: Add "/etc/ansible/hosts"
      blockinfile:
        dest: /etc/ansible/hosts
        block: |
          [CentOS]
          node01
          node02

    - name : Install sshpass
      yum:
        name: sshpass
        state: present